import json
import os
from typing import Any, Dict, List, Literal, Type

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

from clistetradeai.config.trading_config import get_risk_config, get_sentiment_config


class CompressedSentimentOutput(BaseModel):
    overall_sentiment: Literal["bullish", "bearish", "mixed", "neutral"]
    confidence_score: int = Field(ge=0, le=100)
    major_themes: list[str]
    macroeconomic_implications: list[str]
    market_narrative: str
    bullish_pressure_indicators: list[str]
    bearish_pressure_indicators: list[str]
    conflicting_narratives: list[str]
    key_supporting_headlines: list[str]
    key_supporting_events: list[str]


class SentimentCompressorInput(BaseModel):
    sentiment_data: Dict[str, Any] = Field(..., description="SentimentDataFetcherTool output")
    asset_type: str | None = None
    ticker: str | None = None
    trading_style: str | None = None
    risk_tolerance: str = "moderate"
    model: str = "gpt-4o-mini"
    use_llm: bool = True


class SentimentCompressorTool(BaseTool):
    name: str = "Sentiment Compressor Tool"
    description: str = (
        "Compresses raw financial news and macroeconomic events into structured "
        "sentiment intelligence. It does not make BUY, SELL, or HOLD decisions."
    )
    args_schema: Type[BaseModel] = SentimentCompressorInput

    def _run(
        self,
        sentiment_data: Dict[str, Any],
        asset_type: str | None = None,
        ticker: str | None = None,
        trading_style: str | None = None,
        risk_tolerance: str = "moderate",
        model: str = "gpt-4o-mini",
        use_llm: bool = True,
    ) -> dict:
        resolved_asset_type = asset_type or sentiment_data.get("asset_type", "")
        resolved_ticker = ticker or sentiment_data.get("ticker", "")
        resolved_style = trading_style or sentiment_data.get("trading_style")
        sentiment_config = get_sentiment_config(resolved_style)
        risk_config = get_risk_config(risk_tolerance)
        articles = sentiment_data.get("articles", [])
        events = sentiment_data.get("economic_events", [])

        if not articles and not events:
            return {
                "success": False,
                "error": "No articles or economic events available for sentiment compression",
                "asset_type": resolved_asset_type,
                "ticker": resolved_ticker,
                "trading_style": sentiment_config["trading_style"],
            }

        if use_llm and os.getenv("OPENAI_API_KEY"):
            compressed = self._compress_with_openai(
                asset_type=resolved_asset_type,
                ticker=resolved_ticker,
                sentiment_config=sentiment_config,
                risk_tolerance=str(risk_config["risk_tolerance"]),
                model=model,
                articles=articles,
                events=events,
            )
            if compressed["success"]:
                return compressed

        compressed_output = self._compress_deterministically(
            articles=articles,
            events=events,
            sentiment_config=sentiment_config,
        )
        return {
            "success": True,
            "compression_mode": "deterministic_fallback",
            "asset_type": resolved_asset_type,
            "ticker": resolved_ticker,
            "trading_style": sentiment_config["trading_style"],
            "risk_tolerance": risk_config["risk_tolerance"],
            "timeframe": sentiment_data.get("timeframe", {}),
            "source_counts": {
                "articles": len(articles),
                "economic_events": len(events),
            },
            **compressed_output.model_dump(),
            "decision": None,
            "decision_policy": "No BUY, SELL, or HOLD decisions are generated by this tool.",
        }

    def _compress_with_openai(
        self,
        asset_type: str,
        ticker: str,
        sentiment_config: dict[str, Any],
        risk_tolerance: str,
        model: str,
        articles: list[dict[str, Any]],
        events: list[dict[str, Any]],
    ) -> dict:
        try:
            from openai import OpenAI

            client = OpenAI()
            payload = {
                "asset_type": asset_type,
                "ticker": ticker,
                "trading_style": sentiment_config["trading_style"],
                "sentiment_focus": sentiment_config["sentiment_focus"],
                "compression_style": sentiment_config["sentiment_compression"],
                "risk_tolerance": risk_tolerance,
                "articles": articles[: int(sentiment_config["sentiment_max_articles"])],
                "economic_events": events[: int(sentiment_config["sentiment_max_events"])],
            }
            prompt = (
                "Compress raw financial news and macroeconomic events into structured "
                "market sentiment intelligence for a downstream Sentiment Agent. "
                "Do not provide trading recommendations and do not output BUY, SELL, or HOLD. "
                "For swing trading, emphasize earnings trends, macro shifts, rate outlook, "
                "institutional sentiment, and broad narratives. For last_3_days, emphasize "
                "breaking news, analyst actions, short-term catalysts, and sudden macro reactions. "
                "Return only the requested structured JSON fields."
            )
            response = client.responses.parse(
                model=model,
                input=[
                    {"role": "system", "content": prompt},
                    {"role": "user", "content": json.dumps(payload, ensure_ascii=False)},
                ],
                text_format=CompressedSentimentOutput,
            )
            parsed = response.output_parsed
            return {
                "success": True,
                "compression_mode": "llm_structured_output",
                "asset_type": asset_type,
                "ticker": ticker,
                "trading_style": sentiment_config["trading_style"],
                "risk_tolerance": risk_tolerance,
                **parsed.model_dump(),
                "decision": None,
                "decision_policy": "No BUY, SELL, or HOLD decisions are generated by this tool.",
            }
        except Exception as exc:
            fallback = self._compress_deterministically(
                articles=articles,
                events=events,
                sentiment_config=sentiment_config,
            )
            return {
                "success": True,
                "compression_mode": "deterministic_fallback_after_llm_error",
                "llm_error": str(exc),
                "asset_type": asset_type,
                "ticker": ticker,
                "trading_style": sentiment_config["trading_style"],
                "risk_tolerance": risk_tolerance,
                **fallback.model_dump(),
                "decision": None,
                "decision_policy": "No BUY, SELL, or HOLD decisions are generated by this tool.",
            }

    def _compress_deterministically(
        self,
        articles: list[dict[str, Any]],
        events: list[dict[str, Any]],
        sentiment_config: dict[str, Any],
    ) -> CompressedSentimentOutput:
        bullish_terms = ["beat", "upgrade", "growth", "bullish", "surge", "rally", "profit", "strong", "cuts rates"]
        bearish_terms = ["miss", "downgrade", "weak", "bearish", "drop", "lawsuit", "inflation", "recession", "hike"]
        article_texts = [
            f"{article.get('title', '')} {article.get('description', '')}".strip()
            for article in articles
        ]
        event_texts = [
            f"{event.get('event', '')} {event.get('country', '')} actual {event.get('actual')} estimate {event.get('estimate')}".strip()
            for event in events
        ]
        combined = " ".join([*article_texts, *event_texts]).lower()
        bullish_score = sum(combined.count(term) for term in bullish_terms)
        bearish_score = sum(combined.count(term) for term in bearish_terms)

        if bullish_score > bearish_score:
            sentiment = "bullish"
        elif bearish_score > bullish_score:
            sentiment = "bearish"
        elif bullish_score or bearish_score:
            sentiment = "mixed"
        else:
            sentiment = "neutral"

        total_score = bullish_score + bearish_score
        confidence = 40 if total_score == 0 else int(50 + abs(bullish_score - bearish_score) / total_score * 50)
        confidence = min(max(confidence, 0), 100)

        macro_events = [event.get("event", "") for event in events if event.get("event")]
        headlines = [article.get("title", "") for article in articles if article.get("title")]
        major_themes = self._extract_themes([*article_texts, *macro_events])

        return CompressedSentimentOutput(
            overall_sentiment=sentiment,
            confidence_score=confidence,
            major_themes=major_themes,
            macroeconomic_implications=macro_events[:5] or ["No major macroeconomic event context retrieved"],
            market_narrative=(
                f"{sentiment_config['trading_style']} sentiment context is {sentiment}; "
                f"compression focus: {sentiment_config['sentiment_focus']}."
            ),
            bullish_pressure_indicators=self._matching_phrases(article_texts, bullish_terms),
            bearish_pressure_indicators=self._matching_phrases(article_texts, bearish_terms),
            conflicting_narratives=["Bullish and bearish terms both present"] if bullish_score and bearish_score else [],
            key_supporting_headlines=headlines[:7],
            key_supporting_events=macro_events[:7],
        )

    def _extract_themes(self, texts: list[str]) -> list[str]:
        theme_keywords = {
            "earnings": ["earnings", "guidance", "revenue", "profit"],
            "analyst sentiment": ["upgrade", "downgrade", "price target", "analyst"],
            "monetary policy": ["fomc", "fed", "ecb", "interest rate", "central bank"],
            "inflation": ["cpi", "inflation", "prices"],
            "growth": ["gdp", "growth", "pmi"],
            "labor market": ["nfp", "nonfarm", "unemployment", "jobs"],
        }
        combined = " ".join(texts).lower()
        themes = [
            theme
            for theme, keywords in theme_keywords.items()
            if any(keyword in combined for keyword in keywords)
        ]
        return themes or ["general market sentiment"]

    def _matching_phrases(self, texts: list[str], terms: list[str]) -> list[str]:
        matches = []
        for text in texts:
            lowered = text.lower()
            if any(term in lowered for term in terms):
                matches.append(text[:220])
        return matches[:7]
